# Generated by Django 6.0.6 on 2026-09-07 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('state', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Screen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('screen_type', models.CharField(choices=[('standard', 'Standard'), ('imax', 'IMAX'), ('4dx', '4DX'), ('dolby', 'Dolby Cinema')], default='standard', max_length=20)),
                ('total_seats', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SeatCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('color_code', models.CharField(default='#FFFFFF', max_length=7)),
                ('price_multiplier', models.DecimalField(decimal_places=2, default=1.0, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shows', to='movies.movie')),
                ('screen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shows', to='theaters.screen')),
            ],
        ),
        migrations.CreateModel(
            name='ShowSeatPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theaters.seatcategory')),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_prices', to='theaters.show')),
            ],
        ),
        migrations.CreateModel(
            name='Theater',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='theaters/')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theaters', to='theaters.city')),
            ],
        ),
        migrations.AddField(
            model_name='screen',
            name='theater',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screens', to='theaters.theater'),
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_label', models.CharField(max_length=5)),
                ('seat_number', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('screen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='theaters.screen')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='theaters.seatcategory')),
            ],
            options={
                'ordering': ['row_label', 'seat_number'],
                'unique_together': {('screen', 'row_label', 'seat_number')},
            },
        ),
        migrations.AddIndex(
            model_name='show',
            index=models.Index(fields=['movie', 'start_time'], name='theaters_sh_movie_i_48bb2a_idx'),
        ),
        migrations.AddIndex(
            model_name='show',
            index=models.Index(fields=['screen', 'start_time'], name='theaters_sh_screen__748061_idx'),
        ),
        migrations.AddIndex(
            model_name='show',
            index=models.Index(fields=['start_time'], name='theaters_sh_start_t_fcf622_idx'),
        ),
        migrations.AddIndex(
            model_name='show',
            index=models.Index(fields=['is_active', 'start_time'], name='theaters_sh_is_acti_adee29_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='showseatprice',
            unique_together={('show', 'category')},
        ),
        migrations.AddIndex(
            model_name='theater',
            index=models.Index(fields=['city', 'is_active'], name='theaters_th_city_id_014a38_idx'),
        ),
    ]
